from Myro import *
init("sim")
penDown()
size=float(input("Size?"))
def Square():
    forward(size,1)
    turnBy(30)
    turnBy(30)
    turnBy(30)
    forward(size,1)
    turnBy(30)
    turnBy(30)
    turnBy(30)
    forward(size,1)
    turnBy(30)
    turnBy(30)
    turnBy(30)
    forward(size,1)
    turnBy(30)
    turnBy(30)
    turnBy(30)
Square()
